[package]
name = "rot13_encryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chiphers"
path = "src/lib.rs"

[dependencies]
rsa = "0.9.6"
rand = "0.8.4"
base64 = "0.21.7"
