[package]
name = "rot13_encryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# TODO - Add the encryptors library
name = ""
path = ""


[dependencies]
